### ISSUE TITLE
Create version agnostic artifact for Latest release 

### ISSUE THREAD

**Issue by socketbox** [pbs/gorson#71]
GitHub allows for a redirect such that a URL in the form of `https://github.com//owner/name/releases/latest/download/asset-name.zip` is redirected to the release tagged `Latest`. However, if there is no artifact named `asset-latest.zip` (or something similarly version agnostic), then that request will fail.

It would be nice to avoid hard-coding a version in URLs used to retrieve gorson. For example, in pbsorg Dockerfile, we have this:
`RUN wget https://github.com/pbs/gorson/releases/download/4.2.0/gorson-4.2.0-linux-amd64` (now woefully out-of-date). This would  be avoided with the kind of indirection suggested.

**Comment by yhakbar** [comment]
Completed with #72
